language: python
python:
  - "3.9.0"

before_install:
    - python3 -m pip install -U pip
    - pip3 install -U setuptools wheel

install:
  - pip3 install -r requirements-test.txt

script: pytest --cov=hanno

after_success:
  - bash <(curl -s https://codecov.io/bash)
