dist: xenial
language: python
python:
  - "3.9"
  - "nightly"

before_install:
    - python3 -m pip install -U pip

install:
  - pip install -r requirements-test.txt

script: pytest

after_success:
  - codecov
